### ISSUE TITLE
Documentation to build on rhel like distro (rocky Linux) 

### ISSUE THREAD

**Issue by Neurozone** [NumanTF2/ubports-smt285-gtexslte#1]
Hello, I have a server with rocky Linux 9.4 on it.
Do you have the documentation on how to build Ubuntu touch on it for sm-t285 ?

**Comment by NumanTF2** [comment]
it should be somewhat the same just install the dependencies and tools using rhel's package manager

**Comment by NumanTF2** [comment]
btw idek but this repo might be incomplete so just to be safe. download this one Which i know for sure is the full  source https://drive.google.com/file/d/1-LmzaKo4TP0erpNO9jaVAlNuF_nbm-q4/view ill update this repo later to include the entire repo
